<?php

/**
 * @var $model app\forms\SignupForm;
 */

use yii\helpers\Html;
use yii\bootstrap4\ActiveForm;

$this->title = 'Создание пользователя';
?>
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2"><?= Html::encode($this->title) ?></h1>
</div>
<?= \app\widgets\Alert::widget() ?>
<div class="">
    <div class="row">
        <div class="col-6">
            <?php $form = ActiveForm::begin([
                'layout' => 'default',
                'fieldConfig' => ['template' => "{beginWrapper}\n{input}\n{hint}\n{error}\n{endWrapper}"]
            ]) ?>
            <div class="form-row">
                <div class="col">
                    <?= $form->field($model, 'username')->textInput([
                        'placeholder' => 'Логин', 'class' => 'form-control'
                    ]) ?>
                </div>
                <div class="col">
                    <?= $form->field($model, 'email')->textInput([
                        'placeholder' => 'Электронная почта', 'class' => 'form-control'
                    ]) ?>
                </div>
            </div>
            <div class="form-row">
                <div class="col">
                    <?= $form->field($model, 'password')->passwordInput([
                        'placeholder' => 'Пароль', 'class' => 'form-control'
                    ])?>
                </div>
                <div class="col">
                    <?= $form->field($model, 'password_repeat')->passwordInput([
                        'placeholder' => 'Повторите пароль', 'class' => 'form-control'
                    ]) ?>.
                </div>
                <div id="autogenerated-pass-col" class="col">
                    <?= Html::textInput('autogenerated', null, [
                        'placeholder' => 'Пароль',
                        'id' => 'autogenerated-pass',
                        'class' => 'form-control',
                        'disabled' => true,
                        'style' => 'display: none;'
                    ]) ?>
                </div>
            </div>
            <div class="form-row">
                <div class="col">
                    <p class="text-muted font-italic font-weight-light">При выборе типа пользователя "Студент" - поле "Пароль" заполняется автоматически.</p>
                </div>
            </div>
            <div class="form-row">
                <div class="col">
                    <?= $form->field($model, 'lastName')->textInput([
                        'placeholder' => 'Фамилия', 'class' => 'form-control'
                    ]) ?>
                </div>
                <div class="col">
                    <?= $form->field($model, 'firstName')->textInput([
                        'placeholder' => 'Имя', 'class' => 'form-control'
                    ]) ?>
                </div>
                <div class="col">
                    <?= $form->field($model, 'secondName')->textInput([
                        'placeholder' => 'Отчество', 'class' => 'form-control'
                    ]) ?>
                </div>
            </div>

            <div class="form-group">
                <?= $form->field($model, 'role')->dropdownList($model->items, $model->params) ?>
            </div>
            <?= Html::submitButton("Создать", [
                'class' => 'btn btn-primary'
            ]); ?>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

<script type="application/javascript">
    function getRandomPassword() {
        let length = 8,
            charset = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789",
            password = "";

        for (let i = 0, n = charset.length; i < length; ++i) {
            password += charset.charAt(Math.floor(Math.random() * n));
        }

        return password;
    }

    document.getElementById('signupform-role').addEventListener('change', function (event) {
        if (event.target.value === 'student') {
            let password = getRandomPassword()

            document.getElementById('signupform-password').value = password
            document.getElementById('signupform-password_repeat').value = password
            document.getElementById('autogenerated-pass').value = password
            document.getElementById('autogenerated-pass').style.display = 'block'
        } else {
            document.getElementById('signupform-password').value = ''
            document.getElementById('signupform-password_repeat').value = ''
            document.getElementById('autogenerated-pass').style.display = 'none'
        }
    })
</script>